### ISSUE TITLE
Doesn't work properly if view was presented "Form Sheet" or "Page Sheet"

### ISSUE THREAD

**Issue by ghost** [podkovyrin/Keyboardy#20]
Please check [this.](https://github.com/evgenyneu/UnderKeyboard/issues/14)

**Comment by podkovyrin** [comment]
@projectvim 
The issue you are referring to doesn't have any details on how Keyboardy is related to it.
Please, provide an example project which reproduces the wrong behavior.

**Comment by ghost** [comment]
@podkovyrin I have modified `Example` to show the bug. Check it [here](https://github.com/projectvim/Keyboardy).

**Comment by podkovyrin** [comment]
@projectvim This is not a bug in the library. It's up to the client's code how to handle the keyboard notification. 
In your case, I wouldn't use `UIModalPresentationStyle.formSheet` with a text field on the bottom since it's rather impossible to customize its layout/position on the screen because it's a system presentation you cannot tweak. I would rather do a controller with a look'n'feel of formSheet shown with a custom transition.

**Comment by ghost** [comment]
The problem is that I try to use it in an Autofill Extension where I don’t has control how is the view presented.

**Comment by podkovyrin** [comment]
I guess you can do the layout of that controller in a way when the text field is not covered with a keyboard then.
